import { allPosts } from "contentlayer/generated"
import { BookIcon, ChevronRightIcon } from "lucide-react"
import { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by nopnapatn",
}

export default function Blog() {
  return (
    <>
      <div className="max-w-[85rem] px-4 sm:px-6 lg:px-8 mx-auto">
        <div className="grid lg:grid-cols-3 gap-y-8 lg:gap-y-0 lg:gap-x-12">
          <div className="bg-primary-foreground border rounded-md min-h-screen lg:col-span-1 lg:w-full lg:h-full">
            <div className="sticky top-10 start-0 py-8 lg:ps-8"></div>
          </div>
          <div className="lg:col-span-2">
            <div className="py-8 lg:pe-8">
              <div className="space-y-5 lg:space-y-8">
                <div>
                  {allPosts
                    .sort((a, b) => {
                      if (new Date(a.date) > new Date(b.date)) {
                        return -1
                      }
                      return 1
                    })
                    .map((post) => (
                      <Link
                        key={post.url}
                        className="group flex gap-y-6 w-full h-full hover:bg-gray-100 rounded-lg p-5 transition-all dark:hover:bg-white/[.075] dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"
                        href={`/blog/${post.title}`}
                      >
                        <BookIcon className="flex-shrink-0 w-8 h-8 mt-0.5 me-6" />
                        <div>
                          <div>
                            <h3 className="block font-bold text-2xl text-primary">
                              <p>{post.title}</p>
                            </h3>
                            <p className="text-gray-600 dark:text-gray-400 overflow-hidden max-h-72">
                              {post.description}
                            </p>
                          </div>

                          <p className="mt-3 inline-flex items-center gap-x-1 text-sm font-semibold text-gray-800 dark:text-gray-200">
                            Learn more
                            <ChevronRightIcon className="h-4 w-4" />
                          </p>
                        </div>
                      </Link>
                    ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
